ALTER TABLE products ADD COLUMN category VARCHAR(20);
ALTER TABLE products ADD COLUMN item_type VARCHAR(20);

UPDATE products
SET category = CASE
    WHEN type IN ('RENTAL_SPOT', 'RENTAL_ITEM') THEN 'RENTAL'
    WHEN type = 'SALE' THEN 'SALE'
    ELSE 'RENTAL'
END
WHERE category IS NULL;

UPDATE products
SET item_type = CASE
    WHEN type = 'RENTAL_SPOT' THEN 'SPOT'
    WHEN type = 'RENTAL_ITEM' THEN 'EQUIPMENT'
    WHEN type = 'SALE' THEN 'GOODS'
    ELSE 'EQUIPMENT'
END
WHERE item_type IS NULL;

ALTER TABLE products ALTER COLUMN category SET NOT NULL;
ALTER TABLE products ALTER COLUMN item_type SET NOT NULL;
